/* Auto-generated from constants.tsx — config defaults & HUD sizes */
const VERSIONS = ['v4', 'v5', 'v6'];

const HUD_SIZES = {
  armorhud: { w: 32, h: 64, icon: 'fa-shield-halved' },
  offhandhud: { w: 18, h: 18, icon: 'fa-hand' },
  f1button: { w: 18, h: 18, icon: 'fa-eye-slash' },
  f8button: { w: 18, h: 18, icon: 'fa-camera' },
  playerlist: { w: 18, h: 18, icon: 'fa-users' },
  bowindicator: { w: 18, h: 18, icon: 'fa-bullseye' },
  hotbar: { w: 180, h: 18, icon: 'fa-grip-lines' },
  hotbar_left_button: { w: 22, h: 22, icon: 'fa-chevron-left' },
  hotbar_right_button: { w: 22, h: 22, icon: 'fa-chevron-right' },
  fpscounter: { w: 64, h: 32, icon: 'fa-tachometer-alt' },
  clockcompass: { w: 64, h: 32, icon: 'fa-clock' },
  statushud: { w: 64, h: 32, icon: 'fa-heartbeat' },
  slotcounter: { w: 64, h: 32, icon: 'fa-th-large' },
  timerhud: { w: 64, h: 32, icon: 'fa-hourglass-half' },
  dayevent: { w: 64, h: 32, icon: 'fa-calendar-day' },
  chunkmap: { w: 64, h: 64, icon: 'fa-map' },
  directionhud: { w: 128, h: 16, icon: 'fa-compass' },
  forcecoords: { w: 70, h: 40, icon: 'fa-location-dot' },
  targethud: { w: 70, h: 35, icon: 'fa-crosshairs' },
  scoreboard: { w: 70, h: 100, icon: 'fa-list-ol' },
  coordinates: { w: 64, h: 32, icon: 'fa-map-pin' },
  daycounter: { w: 64, h: 32, icon: 'fa-sun' },
  creeperrange: { w: 64, h: 32, icon: 'fa-bomb' },
  expcalculator: { w: 64, h: 32, icon: 'fa-graduation-cap' },
  inventoryhud: { w: 64, h: 32, icon: 'fa-briefcase' },
  lowdurability: { w: 64, h: 32, icon: 'fa-hammer' },
  mainhandhud: { w: 64, h: 32, icon: 'fa-hand-back-fist' },
  speedometer: { w: 128, h: 16, icon: 'fa-gauge-high' },
  walkdistance: { w: 64, h: 32, icon: 'fa-walking' },
  serverdisplay: { w: 64, h: 32, icon: 'fa-server' }
};

const DEFAULT_CONFIGS = {
  v4: {
    "mod_menu_config@gc.pnl": {
      "$armorhud": false,
      "$armorhud_anchor|default": "bottom_right",
      "$armorhud_offset|default": [0, -108],
      "$chat": true,
      "$chat_opacity|default": 0.7,
      "$chat_toggle_index": 0,
      "$coordinates": true,
      "$coordinates_opacity|default": 0.7,
      "$hide_chunkcoordinates": true,
      "$hide_nethercoordinates": true,
      "$hide_nethercoordinates_in_overworld": true,
      "$hide_vanillacordinates": false,
      "$creeperrange": false,
      "$creeperrange_anchor|default": "bottom_right",
      "$creeperrange_offset|default": [-1, -75],
      "$creeperrange_opacity|default": 0.7,
      "$daycounter": false,
      "$daycounter_anchor|default": "bottom_left",
      "$daycounter_offset|default": [1, -20],
      "$daycounter_opacity|default": 0.7,
      "$dayevent": false,
      "$dayevent_anchor|default": "bottom_left",
      "$dayevent_offset|default": [62, -20],
      "$dayevent_opacity|default": 0.7,
      "$directionhud": false,
      "$directionhud_rotation": false,
      "$directionhud_anchor|default": "top_middle",
      "$directionhud_offset|default": [0, 20],
      "$directionhud_opacity|default": 0.7,
      "$expcalculator": false,
      "$expcalculator_anchor|default": "bottom_left",
      "$expcalculator_offset|default": [1, -1],
      "$expcalculator_opacity|default": 0.7,
      "$forcecoords": false,
      "$forcecoords_anchor|default": "top_right",
      "$forcecoords_offset|default": [-1, 1],
      "$forcecoords_opacity|default": 0.7,
      "$fpscounter": false,
      "$fpscounter_anchor|default": "bottom_left",
      "$fpscounter_offset|default": [1, -39],
      "$fpscounter_opacity|default": 0.7,
      "$hudpopup": true,
      "$inventoryhud": false,
      "$inventoryhud_anchor|default": "bottom_right",
      "$inventoryhud_offset|default": [0, -1],
      "$inventoryhud_opacity|default": 0.7,
      "$hide_inventoryhud_durability": false,
      "$hide_inventoryhud_stack": false,
      "$itemcounters": false,
      "$potioncounter": true,
      "$lingering_potion_counter_item_id": 595,
      "$potion_counter_item_id": 453,
      "$splash_potion_counter_item_id": 594,
      "$totemcounter": true,
      "$totem_counter_item_id": 601,
      "$arrowcounter": true,
      "$arrow_counter_item_id": 325,
      "$lowdurability": false,
      "$lowdurability_anchor|default": "bottom_right",
      "$lowdurability_offset|default": [-1, -94],
      "$lowdurability_opacity|default": 0.7,
      "$mainhandhud": false,
      "$hide_mainhandhud_durability": false,
      "$hide_mainhandhud_stack": false,
      "$mainhandhud_slot_opacity": 1.0,
      "$offhandhud": false,
      "$offhandhud_anchor|default": "bottom_middle",
      "$offhandhud_offset|default": [-100, -1],
      "$playerlist": false,
      "$slotcounter": false,
      "$slotcounter_anchor|default": "bottom_left",
      "$slotcounter_offset|default": [62, -39],
      "$slotcounter_opacity|default": 0.7,
      "$speedometer": false,
      "$speedometer_anchor|default": "top_middle",
      "$speedometer_offset|default": [0, 39],
      "$speedometer_opacity|default": 0.7,
      "$statushud": false,
      "$statushud_anchor|default": "bottom_left",
      "$statushud_offset|default": [1, -58],
      "$statushud_opacity|default": 0.7,
      "$targethud": false,
      "$targethud_anchor|default": "top_right",
      "$targethud_offset|default": [-1, 47],
      "$targethud_opacity|default": 0.7,
      "$timerhud": false,
      "$timerhud_anchor|default": "bottom_left",
      "$timerhud_offset|default": [62, -58],
      "$timerhud_opacity|default": 0.7,
      "$walkdistance": false,
      "$walkdistance_anchor|default": "bottom_right",
      "$walkdistance_offset|default": [-1, -56],
      "$walkdistance_opacity|default": 0.7,
      "$hide_item_name_text": false,
      "$hide_jukebox_text": false,
      "$hide_tip_text": false,
      "$hide_actionbar_text": false,
      "$show_safezone": false,
      "$show_clock_compass": false,
      "$compass_aux": 22609920,
      "$clock_aux": 22740992,
      "$recovery_compass_aux": 44695552,
      "$hide_bossname": false,
      "$hide_bossbar": false,
      "$show_boss_health": false,
      "$hide_scoreboard": false,
      "$hide_scoreboard_numbers": false,
      "$hide_hotbar_item_count": false,
      "$hide_creative_xp_bar": false,
      "$show_xp_percentage": false,
      "$show_hotbar_numbers": false,
      "$hotbar_number1": "1",
      "$hotbar_number2": "2",
      "$hotbar_number3": "3",
      "$hotbar_number4": "4",
      "$hotbar_number5": "5",
      "$hotbar_number6": "6",
      "$hotbar_number7": "7",
      "$hotbar_number8": "8",
      "$hotbar_number9": "9",
      "$crosshair_default_preset_index": 1,
      "$hide_crosshair": false,
      "$rgb_crosshair": false,
      "$brighter": false,
      "$aqua_saturation": false,
      "$red_saturation": false,
      "$yellow_saturation": false,
      "$blue_saturation": false,
      "$nightshift": false
    },
    "pause_menu_config@gc.pnl": {
      "$glacier_playername": false,
      "$glacier_worldname": false
    },
    "container_config@gc.pnl": {
      "$force_autoplace_mode": false,
      "$hide_hover_item_id": false,
      "$hide_hover_item_aux_id": false
    },
    "namespace": "gc"
  },
  v5: {
    "mod_menu_config@gc.pnl": {
      "$armorhud": false,
      "$armorhud_anchor|default": "bottom_right",
      "$armorhud_offset|default": [0, -108],
      "$bowindicator": false,
      "$bowindicator_opacity|default": 0.7,
      "$bowindicator_anchor|default": "left_middle",
      "$bowindicator_offset|default": [2, 0],
      "$chat": true,
      "$chat_opacity|default": 0.7,
      "$chat_toggle_index": 0,
      "$chunkmap": false,
      "$chunkmap_anchor|default": "top_left",
      "$chunkmap_offset|default": [2, 2],
      "$chunkmap_opacity|default": 0.7,
      "$chunkmap_chunk_position|default": false,
      "$hide_slime_chunks|default": false,
      "$coordinates": true,
      "$coordinates_opacity|default": 0.7,
      "$hide_chunkcoordinates": true,
      "$hide_nethercoordinates": true,
      "$hide_nethercoordinates_in_overworld": true,
      "$hide_vanillacordinates": false,
      "$daycounter": false,
      "$daycounter_anchor|default": "bottom_left",
      "$daycounter_offset|default": [1, -20],
      "$daycounter_opacity|default": 0.7,
      "$dayevent": false,
      "$dayevent_anchor|default": "bottom_left",
      "$dayevent_offset|default": [62, -20],
      "$dayevent_opacity|default": 0.7,
      "$directionhud": false,
      "$directionhud_rotation": false,
      "$directionhud_anchor|default": "top_middle",
      "$directionhud_touch_offset": [9, 20],
      "$directionhud_mouse_controller_offset": [0, 4],
      "$directionhud_opacity|default": 0.7,
      "$expcalculator": false,
      "$expcalculator_anchor|default": "bottom_left",
      "$expcalculator_offset|default": [1, -1],
      "$expcalculator_opacity|default": 0.7,
      "$forcecoords": false,
      "$forcecoords_anchor|default": "top_right",
      "$forcecoords_offset|default": [-1, 1],
      "$forcecoords_opacity|default": 0.7,
      "$fpscounter": false,
      "$fpscounter_anchor|default": "bottom_left",
      "$fpscounter_offset|default": [1, -39],
      "$fpscounter_opacity|default": 0.7,
      "$hudpopup": true,
      "$hotbar": true,
      "$hide_hotbar_item_count": false,
      "$hide_creative_xp_bar": false,
      "$hide_xp_percentage": false,
      "$hide_inventory_button": false,
      "$hide_hotbar_numbers": false,
      "$hotbar_number1": "1",
      "$hotbar_number2": "2",
      "$hotbar_number3": "3",
      "$hotbar_number4": "4",
      "$hotbar_number5": "5",
      "$hotbar_number6": "6",
      "$hotbar_number7": "7",
      "$hotbar_number8": "8",
      "$hotbar_number9": "9",
      "$hotbar_toggle_index": 0,
      "$inventoryhud": false,
      "$inventoryhud_toggle_index": 0,
      "$inventoryhud_anchor|default": "bottom_right",
      "$inventoryhud_offset|default": [0, -1],
      "$inventoryhud_opacity|default": 0.7,
      "$hide_inventoryhud_durability": false,
      "$hide_inventoryhud_stack": false,
      "$show_inventoryhud_numbers": false,
      "$itemcounters": false,
      "$hide_potioncounter": true,
      "$lingering_potion_counter_item_id": 595,
      "$potion_counter_item_id": 453,
      "$splash_potion_counter_item_id": 594,
      "$hide_totemcounter": true,
      "$totem_counter_item_id": 601,
      "$hide_arrowcounter": true,
      "$arrow_counter_item_id": 325,
      "$lowdurability": false,
      "$lowdurability_anchor|default": "bottom_right",
      "$lowdurability_offset|default": [-1, -75],
      "$lowdurability_opacity|default": 0.7,
      "$mainhandhud": false,
      "$mainhand_durability_toggle_index": 0,
      "$hide_mainhandhud_total_durability": false,
      "$hide_mainhandhud_stack": false,
      "$hide_mainhandhud_item": false,
      "$mainhandhud_opacity": 0.7,
      "$mainhandhud_touch_offset": [140, -3.5],
      "$mainhandhud_mouse_controller_offset": [130, -3.5],
      "$offhandhud": false,
      "$offhandhud_anchor|default": "bottom_middle",
      "$offhandhud_offset|default": [-113, -1],
      "$playerlist": true,
      "$playerlist_mobile_button_anchor|default": "top_middle",
      "$playerlist_mobile_button_offset|default": [47.5, 1],
      "$playerlist_mobile_button_size|default": [18, 18],
      "$serverdisplay": false,
      "$serverdisplay_anchor|default": "bottom_right",
      "$serverdisplay_offset|default": [-1, -75],
      "$serverdisplay_opacity|default": 0.7,
      "$slotcounter": false,
      "$slotcounter_anchor|default": "bottom_left",
      "$slotcounter_offset|default": [62, -39],
      "$slotcounter_opacity|default": 0.7,
      "$speedometer": false,
      "$speedometer_anchor|default": "top_middle",
      "$speedometer_touch_offset|default": [9, 39],
      "$speedometer_mouse_controller_offset|default": [0, 22],
      "$speedometer_opacity|default": 0.7,
      "$statushud": false,
      "$statushud_anchor|default": "bottom_left",
      "$statushud_offset|default": [1, -58],
      "$statushud_opacity|default": 0.7,
      "$targethud": false,
      "$targethud_anchor|default": "top_right",
      "$targethud_offset|default": [-1, 42],
      "$targethud_opacity|default": 0.7,
      "$timerhud": false,
      "$timerhud_anchor|default": "bottom_left",
      "$timerhud_offset|default": [62, -58],
      "$timerhud_opacity|default": 0.7,
      "$walkdistance": false,
      "$walkdistance_anchor|default": "bottom_right",
      "$walkdistance_offset|default": [-1, -56],
      "$walkdistance_opacity|default": 0.7,
      "$hide_item_name_text": false,
      "$hide_jukebox_text": false,
      "$hide_tip_text": false,
      "$hide_actionbar_text": false,
      "$show_safezone": false,
      "$show_clock_compass": false,
      "$compass_aux": 27328512,
      "$clock_aux": 27459584,
      "$recovery_compass_aux": 44761088,
      "$bossbar_anchor|default": "top_middle",
      "$bossbar_offset|default": [0, 15],
      "$hide_bossname": false,
      "$hide_bossbar": false,
      "$show_boss_health": false,
      "$scoreboard_anchor|default": "right_middle",
      "$scoreboard_offset|default": [0, 0],
      "$hide_scoreboard": false,
      "$hide_scoreboard_numbers": false,
      "$crosshair_default_preset_index": 1,
      "$hide_crosshair": false,
      "$rgb_crosshair": false,
      "$brighter": false,
      "$aqua_display": false,
      "$red_display": false,
      "$yellow_display": false,
      "$blue_display": false,
      "$orange_display": false,
      "$purple_display": false,
      "$green_display": false,
      "$display_opacity|default": 1.0
    },
    "pause_menu_config@gc.pnl": {
      "$glacier_playername": false,
      "$glacier_worldname": false
    },
    "container_config@gc.pnl": {
      "$force_autoplace_mode": false,
      "$hide_container_durability": false,
      "$hide_hover_item_id": false,
      "$hide_hover_item_aux_id": false
    },
    "namespace": "gc"
  },
  v6: {
    "mod_menu_config@gc.pnl": {
      "$armorhud": false,
      "$armorhud_anchor|default": "right_middle",
      "$armorhud_offset|default": [-5, -10],
      "$bowindicator": false,
      "$bowindicator_opacity|default": 0.7,
      "$bowindicator_anchor|default": "left_middle",
      "$bowindicator_offset|default": [2, 0],
      "$chat": true,
      "$chat_opacity|default": 0.7,
      "$chat_toggle_index": 0,
      "$chunkmap": false,
      "$chunkmap_anchor|default": "top_left",
      "$chunkmap_offset|default": [2, 2],
      "$chunkmap_opacity|default": 0.7,
      "$chunkmap_chunk_position|default": false,
      "$hide_slime_chunks|default": false,
      "$clockcompass": false,
      "$compass_aux": 425,
      "$clock_aux": 423,
      "$recovery_compass_aux": 688,
      "$clockcompass_anchor|default": "bottom_left",
      "$clockcompass_offset|default": [62, -76],
      "$clockcompass_opacity|default": 0.7,
      "$coordinates": true,
      "$hide_vanillacordinates": false,
      "$coordinates_opacity|default": 0.7,
      "$show_chunkcoordinates": false,
      "$chunk_coordinates_opacity|default": 0.7,
      "$show_nethercoordinates": false,
      "$nether_coordinates_opacity|default": 0.7,
      "$show_nethercoordinates_in_overworld": false,
      "$nether_in_overworld_coordinates_opacity|default": 0.7,
      "$dayevent": false,
      "$dayevent_anchor|default": "bottom_right",
      "$dayevent_offset|default": [-62, -37],
      "$dayevent_opacity|default": 0.7,
      "$debughud": false,
      "$hide_glacierversion": false,
      "$glacierversion_opacity|default": 0.7,
      "$hide_version": false,
      "$version_opacity|default": 0.7,
      "$hide_os_type": false,
      "$os_type_opacity|default": 0.7,
      "$hide_graphics": false,
      "$graphics_opacity|default": 0.7,
      "$hide_platform": false,
      "$platform_opacity|default": 0.7,
      "$hide_ui_type": false,
      "$ui_type_opacity|default": 0.7,
      "$hide_world_type": false,
      "$world_type_opacity|default": 0.7,
      "$hide_world_name": false,
      "$world_name_opacity|default": 0.7,
      "$hide_day_counter": false,
      "$day_counter_opacity|default": 0.7,
      "$hide_moon_phase": false,
      "$moon_phase_opacity|default": 0.7,
      "$hide_gamemode": false,
      "$gamemode_opacity|default": 0.7,
      "$hide_xp_level": false,
      "$xp_level_opacity|default": 0.7,
      "$hide_item_id": false,
      "$item_id_opacity|default": 0.7,
      "$hide_item_aux_id": false,
      "$item_aux_id_opacity|default": 0.7,
      "$directionhud": false,
      "$directionhud_rotation": false,
      "$directionhud_anchor|default": "top_middle",
      "$directionhud_touch_offset": [9, 20],
      "$directionhud_mouse_controller_offset": [0, 4],
      "$directionhud_opacity|default": 0.7,
      "$expcalculator": false,
      "$expcalculator_anchor|default": "bottom_right",
      "$expcalculator_offset|default": [-1, -19],
      "$expcalculator_opacity|default": 0.7,
      "$forcecoords": false,
      "$forcecoords_anchor|default": "top_right",
      "$forcecoords_offset|default": [-1, 1],
      "$forcecoords_opacity|default": 0.7,
      "$fpscounter": false,
      "$fpscounter_anchor|default": "bottom_left",
      "$fpscounter_offset|default": [1, -76],
      "$fpscounter_opacity|default": 0.7,
      "$hudpopup": true,
      "$inventoryhud": false,
      "$inventoryhud_toggle_index": 0,
      "$inventoryhud_anchor|default": "bottom_left",
      "$inventoryhud_offset|default": [18, -1],
      "$inventoryhud_opacity|default": 0.7,
      "$hide_inventoryhud_durability": false,
      "$hide_inventoryhud_stack": false,
      "$show_inventoryhud_numbers": false,
      "$itemcounters": false,
      "$hide_potioncounter": false,
      "$lingering_potion_counter_item_id": 601,
      "$potion_counter_item_id": 459,
      "$splash_potion_counter_item_id": 600,
      "$hide_totemcounter": false,
      "$totem_counter_item_id": 607,
      "$hide_arrowcounter": false,
      "$arrow_counter_item_id": 332,
      "$lowdurability": false,
      "$lowdurability_opacity|default": 0.7,
      "$mainhandhud": false,
      "$mainhand_durability_toggle_index": 0,
      "$hide_mainhandhud_total_durability": false,
      "$hide_mainhandhud_stack": false,
      "$hide_mainhandhud_item": false,
      "$mainhandhud_opacity": 0.7,
      "$mainhandhud_anchor|default": "bottom_right",
      "$mainhandhud_offset|default": [-23, -73],
      "$mobileshortcuts": true,
      "$hide_f1button": false,
      "$f1button_size|default": [18, 18],
      "$f1button_anchor|default": "top_middle",
      "$f1button_offset|default": [66.5, 1],
      "$hide_f8button": false,
      "$f8button_size|default": [18, 18],
      "$f8button_anchor|default": "top_middle",
      "$f8button_offset|default": [-47.5, 1],
      "$hide_hotbar_left_button": false,
      "$hotbar_left_button_size|default": [22, 22],
      "$hotbar_left_button_anchor|default": "bottom_middle",
      "$hotbar_left_button_offset|default": [-113, -2],
      "$hide_hotbar_right_button": false,
      "$hotbar_right_button_size|default": [22, 22],
      "$hotbar_right_button_anchor|default": "bottom_middle",
      "$hotbar_right_button_offset|default": [113, -2],
      "$offhandhud": false,
      "$offhandhud_anchor|default": "bottom_right",
      "$offhandhud_offset|default": [-1, -72.5],
      "$playerlist": true,
      "$hide_playeravatars|default": false,
      "$playerlist_opacity|default": 0.7,
      "$playerlist_mobile_button_anchor|default": "top_middle",
      "$playerlist_mobile_button_offset|default": [47.5, 1],
      "$playerlist_mobile_button_size|default": [18, 18],
      "$safezoneviewer": false,
      "$serverdisplay": false,
      "$serverdisplay_anchor|default": "bottom_right",
      "$serverdisplay_offset|default": [-1, -1],
      "$serverdisplay_opacity|default": 0.7,
      "$shinypotions": false,
      "$slotcounter": false,
      "$slotcounter_anchor|default": "bottom_left",
      "$slotcounter_offset|default": [62, -58],
      "$slotcounter_opacity|default": 0.7,
      "$speedometer": false,
      "$speedometer_anchor|default": "top_middle",
      "$speedometer_touch_offset|default": [9, 39],
      "$speedometer_mouse_controller_offset|default": [0, 22],
      "$speedometer_opacity|default": 0.7,
      "$statushud": false,
      "$statushud_anchor|default": "bottom_left",
      "$statushud_offset|default": [1, -58],
      "$statushud_opacity|default": 0.7,
      "$targethud": false,
      "$targethud_anchor|default": "top_right",
      "$targethud_offset|default": [-1, 42],
      "$targethud_opacity|default": 0.7,
      "$timerhud": false,
      "$timerhud_anchor|default": "bottom_right",
      "$timerhud_offset|default": [-1, -37],
      "$timerhud_opacity|default": 0.7,
      "$walkdistance": false,
      "$walkdistance_anchor|default": "bottom_right",
      "$walkdistance_offset|default": [-1, -55],
      "$walkdistance_opacity|default": 0.7,
      "$hide_item_name_text": false,
      "$hide_jukebox_text": false,
      "$hide_tip_text": false,
      "$hide_actionbar_text": false,
      "$bossbar_anchor|default": "top_middle",
      "$bossbar_offset|default": [0, 15],
      "$hide_bossname": false,
      "$hide_bossbar": false,
      "$show_boss_health": false,
      "$scoreboard_anchor|default": "right_middle",
      "$scoreboard_offset|default": [0, 0],
      "$hide_scoreboard": false,
      "$hide_scoreboard_numbers": false,
      "$hotbar": true,
      "$hide_hotbar_item_count": false,
      "$hide_inventory_button": false,
      "$show_hotbar_numbers": false,
      "$hotbar_number1": "1",
      "$hotbar_number2": "2",
      "$hotbar_number3": "3",
      "$hotbar_number4": "4",
      "$hotbar_number5": "5",
      "$hotbar_number6": "6",
      "$hotbar_number7": "7",
      "$hotbar_number8": "8",
      "$hotbar_number9": "9",
      "$hotbar_toggle_index": 1,
      "$crosshair_default_preset_index": 1,
      "$crosshair_size|default": 0.5,
      "$crosshair_color_default_preset_index": 1,
      "$show_crosshair_outlines": false,
      "$brighter": false,
      "$aqua_display": false,
      "$red_display": false,
      "$yellow_display": false,
      "$blue_display": false,
      "$orange_display": false,
      "$purple_display": false,
      "$green_display": false,
      "$display_opacity|default": 1,
      "$exp_bar_color_default_preset_index": 1,
      "$show_creative_xp_bar": false,
      "$show_xp_percentage": false
    },
    "start_screen_config@gc.pnl": {
      "$ui_switcher_toggle_index": 0
    },
    "pause_menu_config@gc.pnl": {
      "$glacier_playername": false,
      "$glacier_worldname": false
    },
    "container_config@gc.pnl": {
      "$force_autoplace_mode": false,
      "$hide_container_durability": false,
      "$hide_hover_item_id": false,
      "$hide_hover_item_aux_id": false,
      "$hide_suspicious_stew_info": false,
      "$furnace_food_tab_item_id": 304,
      "$furnace_ore_tab_item_id": 56,
      "$furnace_block_tab_item_id": 1,
      "$furnace_fuel_tab_item_id": 333,
      "$raw_beef_item_id": 302,
      "$raw_porkchop_item_id": 291,
      "$raw_chicken_item_id": 304,
      "$raw_mutton_item_id": 589,
      "$raw_rabbit_item_id": 317,
      "$raw_cod_item_id": 293,
      "$raw_salmon_item_id": 294,
      "$potato_item_id": 309,
      "$kelp_item_id": 414,
      "$iron_ore_item_id": 15,
      "$copper_ore_item_id": -311,
      "$gold_ore_item_id": 14,
      "$nether_gold_ore_item_id": -288,
      "$ancient_debris_item_id": -271,
      "$redstone_ore_item_id": 73,
      "$coal_ore_item_id": 16,
      "$emerald_ore_item_id": 129,
      "$lapis_lazuli_ore_item_id": -400,
      "$diamond_ore_item_id": 56,
      "$nether_quartz_ore_item_id": 153,
      "$raw_iron_item_id": 545,
      "$raw_copper_item_id": 547,
      "$raw_gold_item_id": 546,
      "$cobblestone_item_id": 4,
      "$stone_item_id": 1,
      "$stone_bricks_item_id": 98,
      "$cobbled_deepslate_item_id": -379,
      "$deepslate_bricks_item_id": -391,
      "$deepslate_tiles_item_id": -387,
      "$sandstone_item_id": 24,
      "$red_sandstone_item_id": 179,
      "$nether_bricks_item_id": 112,
      "$basalt_item_id": -234,
      "$polished_blackstone_bricks_item_id": -274,
      "$block_of_quartz_item_id": 155,
      "$clay_item_id": 82,
      "$dyed_terracotta_item_id": 172,
      "$sand_item_id": 12,
      "$wet_sponge_item_id": -984,
      "$log_item_id": 17,
      "$wood_item_id": -212,
      "$chorus_fruit_item_id": 598,
      "$sea_pickle_item_id": -156,
      "$cactus_item_id": 81,
      "$clay_ball_item_id": 416,
      "$netherrack_item_id": 87,
      "$iron_tools_item_id": 375,
      "$gold_tools_item_id": 383,
      "$leaves_item_id": 18,
      "$lava_bucket_item_id": 395,
      "$block_of_coal_item_id": 173,
      "$dried_kelp_block_item_id": -139,
      "$blaze_rod_item_id": 455,
      "$coal_item_id": 333,
      "$charcoal_item_id": 334,
      "$boat_item_id": 408,
      "$bamboo_blocks_item_id": -527,
      "$bee_nest_item_id": -218,
      "$beehive_item_id": -219,
      "$chiseled_bookshelf_item_id": -526,
      "$wooden_building_blocks_item_id": 53,
      "$utility_blocks_item_id": 58,
      "$fishing_rod_item_id": 424,
      "$crossbow_item_id": 614,
      "$bow_item_id": 331,
      "$wooden_door_item_id": 391,
      "$sign_item_id": 390,
      "$hanging_sign_item_id": -500,
      "$wooden_tools_item_id": 341,
      "$bowl_item_id": 353,
      "$saplings_item_id": 6,
      "$stick_item_id": 352,
      "$dead_bush_item_id": 32,
      "$azalea_item_id": -337,
      "$leaf_litter_item_id": -1026,
      "$short_dry_grass_item_id": -1028,
      "$tall_dry_grass_item_id": -1029,
      "$bamboo_item_id": -163,
      "$scaffolding_item_id": -165,
      "$wooden_tools_material_item_id": 5,
      "$shields_item_id": 387,
      "$shield_material_item_id": 5,
      "$leather_armors_item_id": 367,
      "$leather_armors_material_item_id": 413,
      "$stone_tools_item_id": 343,
      "$stone_tools_material_item_id": 4,
      "$iron_tools_material_item_id": 336,
      "$golden_tools_item_id": 384,
      "$golden_tools_material_item_id": 337,
      "$diamond_tools_item_id": 381,
      "$diamond_tools_material_item_id": 335,
      "$netherite_tools_item_id": 653,
      "$netherite_tools_material_item_id": 651,
      "$turtle_shell_item_id": 612,
      "$turtle_shell_material_item_id": 611,
      "$elytra_item_id": 603,
      "$elytra_material_item_id": 613,
      "$mace_item_id": 351,
      "$mace_material_item_id": 281,
      "$wolf_armor_item_id": 747,
      "$wolf_armor_material_item_id": 746,
      "$leather_helmet_item_id": 367,
      "$leather_chestplate_item_id": 368,
      "$leather_leggings_item_id": 369,
      "$leather_boots_item_id": 370,
      "$chainmail_helmet_item_id": 371,
      "$chainmail_chestplate_item_id": 372,
      "$chainmail_leggings_item_id": 373,
      "$chainmail_boots_item_id": 374,
      "$iron_helmet_item_id": 375,
      "$iron_chestplate_item_id": 376,
      "$iron_leggings_item_id": 377,
      "$iron_boots_item_id": 378,
      "$golden_helmet_item_id": 383,
      "$golden_chestplate_item_id": 384,
      "$golden_leggings_item_id": 385,
      "$golden_boots_item_id": 386,
      "$diamond_helmet_item_id": 379,
      "$diamond_chestplate_item_id": 380,
      "$diamond_leggings_item_id": 381,
      "$diamond_boots_item_id": 382,
      "$netherite_helmet_item_id": 652,
      "$netherite_chestplate_item_id": 653,
      "$netherite_leggings_item_id": 654,
      "$netherite_boots_item_id": 655,
      "$netherite_upgrade_item_id": 723,
      "$sentry_trim_item_id": 724,
      "$vex_trim_item_id": 730,
      "$wild_trim_item_id": 727,
      "$coast_trim_item_id": 726,
      "$dune_trim_item_id": 725,
      "$wayfinder_trim_item_id": 736,
      "$shaper_trim_item_id": 738,
      "$raiser_trim_item_id": 737,
      "$host_trim_item_id": 739,
      "$ward_trim_item_id": 728,
      "$silence_trim_item_id": 735,
      "$tide_trim_item_id": 731,
      "$snout_trim_item_id": 732,
      "$rib_trim_item_id": 733,
      "$eye_trim_item_id": 729,
      "$spire_trim_item_id": 734,
      "$flow_trim_item_id": 740,
      "$bolt_trim_item_id": 741,
      "$amethyst_shard_item_id": 666,
      "$copper_ingot_item_id": 544,
      "$diamond_item_id": 335,
      "$emerald_item_id": 552,
      "$gold_ingot_item_id": 337,
      "$iron_ingot_item_id": 336,
      "$lapis_lazuli_item_id": 446,
      "$nether_quartz_item_id": 563,
      "$netherite_ingot_item_id": 651,
      "$redstone_dust_item_id": 405,
      "$resin_brick_item_id": 752,
      "$enchanted_book_item_id": 560,
      "$slime_block_item_id": 165,
      "$suspicious_stew_id": 631
    },
    "namespace": "gc"
  }
};

window.GC_DATA = { VERSIONS, HUD_SIZES, DEFAULT_CONFIGS };
